networks: 
  default: 
    name: ds
    external: true
services:
  users_db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=users
      - POSTGRES_PASSWORD=123
  users_web:
    build: .
#    command: uwsgi --http 0.0.0.0:8000 --module distributed.wsgi
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8003:8000"
    environment:
      - DB_NAME=users
      - DB_USER=users
      - DB_PASS=123
      - DB_HOST=users_db
    depends_on:
      - users_db
#  nginx:
#    container_name: nginx_container
#    build: ./nginx
#    ports:
#      - 80:80
